# RT-Thread building script for component

from building import *

Import('rtconfig')

cwd = GetCurrentDir()
src = ['cpu_port.c']
CPPPATH = [cwd]

if rtconfig.CROSS_TOOL == 'mingw':
    src += ['startup_mingw.c']
elif rtconfig.CROSS_TOOL == 'cygwin':
    src += ['startup_cygwin.c']
else:  # msvc
    src += ['startup_msvc.c']

group = DefineGroup('libcpu', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
